package frc8768.robot.subsystems;

import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.units.Units;
import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc8768.robot.util.Constants;
import frc8768.robot.util.MotorType;
import swervelib.SwerveDrive;
import swervelib.math.SwerveMath;
import swervelib.parser.SwerveParser;

import java.io.File;
import java.io.IOException;
import java.util.function.Supplier;

/**
 * Container class for everything Swerve
 */
public class SwerveSubsystem extends SubsystemBase {
    /**
     * SysID routine for the Drive motor of module 0
     */
    private final SysIdRoutine driveSysIdRoutine;

    /**
     * SysID routine for the Angle motor of module 0
     */
    private final SysIdRoutine angleSysIdRoutine;

    /**
     * The underlying YAGSL implementation
     */
    private SwerveDrive swerveDrive;

    /**
     * @param type Neos or Falcons, see {@link MotorType}
     * @throws IOException if it can't find the resources.
     */
    public SwerveSubsystem(MotorType type) throws IOException {
        double metersPerRotation = SwerveMath.calculateMetersPerRotation(Constants.SwerveConfig.WHEEL_DIAMETER, Constants.SwerveConfig.DRIVE_GEAR_RATIO);
        double metersPerDeg = SwerveMath.calculateDegreesPerSteeringRotation(Constants.SwerveConfig.TURN_GEAR_RATIO);

        switch(type) {
            case SPARKMAX -> swerveDrive = new SwerveParser(new File(Filesystem.getDeployDirectory(), "swerve/neo")).createSwerveDrive(Constants.SwerveConfig.MAX_SPEED, metersPerDeg, metersPerRotation);
            case TALONFX -> swerveDrive = new SwerveParser(new File(Filesystem.getDeployDirectory(), "swerve/falcon")).createSwerveDrive(Constants.SwerveConfig.MAX_SPEED, metersPerDeg, metersPerRotation);
            case SPARKFLEX -> swerveDrive = new SwerveParser(new File(Filesystem.getDeployDirectory(), "swerve/sparkflex")).createSwerveDrive(Constants.SwerveConfig.MAX_SPEED, metersPerDeg, metersPerRotation);
        }

        driveSysIdRoutine = new SysIdRoutine(
                new SysIdRoutine.Config(),
                new SysIdRoutine.Mechanism(
                        volt -> swerveDrive.getModules()[0].getDriveMotor().setVoltage(volt.in(Units.Volts)),
                        log -> {
                            // Record a frame for the shooter motor.
                            log.motor("drive-motor")
                                    .voltage(Units.Volts.of(swerveDrive.getModules()[0].getDriveMotor().getVoltage()))
                                    .linearPosition(Units.Meter.of(swerveDrive.getModules()[0].getDriveMotor().getPosition()))
                                    .linearVelocity(
                                            Units.MetersPerSecond.of(swerveDrive.getModules()[0].getDriveMotor().getVelocity()));
                        },
                        null
                )
        );

        angleSysIdRoutine = new SysIdRoutine(
                new SysIdRoutine.Config(),
                new SysIdRoutine.Mechanism(
                        volt -> swerveDrive.getModules()[0].getAngleMotor().setVoltage(volt.in(Units.Volts)),
                        log -> {
                            // Record a frame for the shooter motor.
                            log.motor("angle-motor")
                                    .voltage(Units.Volts.of(swerveDrive.getModules()[0].getAngleMotor().getVoltage()))
                                    .angularPosition(Units.Degree.of(swerveDrive.getModules()[0].getAbsolutePosition()))
                                    .angularVelocity(
                                            Units.DegreesPerSecond.of(swerveDrive.getModules()[0].getAngleMotor().getVelocity()));
                        },
                        null
                )
        );
    }

    /**
     * Move the base in field-relative space
     *
     * @param chassisSpeedSupplier Chassis speeds usually generated by SwerveInputStream
     *
     * @return A command
     */
    public Command drive(Supplier<ChassisSpeeds> chassisSpeedSupplier) {
        return run(() -> swerveDrive.driveFieldOriented(chassisSpeedSupplier.get()));
    }

    /**
     * Move the base in field-relative space
     *
     * @param chassisSpeedSupplier Chassis speeds usually generated by SwerveInputStream
     *
     * @return A command
     */
    public Command driveRobotRelative(Supplier<ChassisSpeeds> chassisSpeedSupplier) {
        return run(() -> swerveDrive.drive(chassisSpeedSupplier.get()));
    }

    /**
     * Get the Gyro rotation in degrees.
     *
     * @return 3d rotation.
     */
    public Rotation3d getGyroRot() {
        return swerveDrive.getGyroRotation3d();
    }

    /**
     * Get the underlying instance.
     *
     * @return Underlying instance
     */
    public SwerveDrive getSwerveDrive() {
        return swerveDrive;
    }

    /**
     * Get the command for SysID Drive
     *
     * @return The associated command
     */
    public Command sysIdQuasistaticDrive(SysIdRoutine.Direction direction) {
        return driveSysIdRoutine.quasistatic(direction);
    }

    /**
     * Get the command for SysID Angle
     *
     * @return The associated command
     */
    public Command sysIdQuasistaticAngle(SysIdRoutine.Direction direction) {
        return angleSysIdRoutine.quasistatic(direction);
    }

    /**
     * Get the command for SysID Drive
     *
     * @return The associated command
     */
    public Command sysIdDynamicDrive(SysIdRoutine.Direction direction) {
        return driveSysIdRoutine.dynamic(direction);
    }

    /**
     * Get the command for SysID Angle
     *
     * @return The associated command
     */
    public Command sysIdDynamicAngle(SysIdRoutine.Direction direction) {
        return angleSysIdRoutine.dynamic(direction);
    }
}
